### PR TITLE
Adds new SBOM structure

### PR DESCRIPTION
**Pull request by ForestEckhardt**
- Now that the lifecycle supports both sbom formats this PR adds the new
sbom format while keeping the old format around for the time being to
allow users to switch over

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [ ] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by thitch97** [comment]
Small thing but the related PR for this in `node-engine` [errs on the side of transparency](https://github.com/paketo-buildpacks/node-engine/blob/1bf448a9600d037d549a262b32ee56cbb5cd7d4a/build.go#L63) in regards to the logging output for SBOM processes. For the sake of consistency it'd be nice to see that done here as well.

**Comment by thitch97** [comment]
@sophiewigmore Thinking about it further, I could see only logging the preferred choice being adequate since the bottom line is that the SBOM is available to users and they may not understand (or care about) the details.

**Comment by ryanmoran** [comment]
I also believe that logging about only one type of SBOM is necessary. I'd prefer to see us log that the new SBOM gets generated and mostly ignore that we also generate the old format.

**Comment by sophiewigmore** [comment]
@ryanmoran it looks like the lifecycle actually logs a warning about the old SBOM format anyways, so we are completely fine to remove our own logs around that.

**Comment by ForestEckhardt** [comment]
@thitch97 @sophiewigmore @ryanmoran  Does this PR actually constitute a `major` version bump? I feel like we are only adding the new BOM format and everything else is staying the same. Is there any reason this wouldn't just be a `minor` bump? Do we want to do a `major` bump anyway cause we feel this is important? Would love your thoughts.

**Comment by sophiewigmore** [comment]
@ForestEckhardt my understanding was that a pre-1.0.0 version would receive a minor version bump when we change the API version. I think this should be a minor bump.
Then, when we remove support for the legacy format, we should remove support for any other features that have deprecation warnings (ex. using buildpack.yml) and cut major versions across the language family.

**Review by ryanmoran — APPROVED** [review]

**Pull request merged**
